name: Generate GitHub Streak

on:
  schedule:
    - cron: "0 0 * * *"   # daily update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate streak card
        uses: DenverCoder1/github-readme-streak-stats@master
        with:
          username: MirzaKhalilUlRehman
          theme: radical
          hide_border: true
          output: assets/streak.svg

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/streak.svg
          git commit -m "Update streak card" || echo "No changes"
          git push
